#server
spring:
  application:
    name: zijinge_blog
  datasource: # datasource
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&serverTimezone=UTC&characterEncoding=utf8&Unicode=useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:  # 配置redis
    host: localhost
    port: 6379
server:
  port: 8888

#  mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志打印
  global-config:
    db-config:
      table-prefix: ms_ #表示表的前缀 为ms_ ,后续在创建pojo类时可以不写前缀