# 服务端口
server:
  port: 8889

spring:
  # 应用名称
  application:
    name: zijinge_admin_blog
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&serverTimezone=UTC&characterEncoding=utf8&Unicode=useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      # 单个文件的最大值
      max-file-size: 2MB
      # 上传文件大小的总值，不超过20MB
      max-request-size: 20MB

#  mybatis-plus
mybatis-plus:
  configuration:
    #日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #表示表的前缀 为ms_ ,后续在创建pojo类时可以不写前缀
      table-prefix: ms_

